name: real_appraiser
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  flutter_modular: ^6.3.3
  http: ^1.2.1
  dartz: ^0.10.1
  fluttertoast: ^8.2.5
  flutter_easyloading: ^3.0.5
  package_info_plus: ^7.0.0
  get_storage: ^2.1.1
  encrypt: ^5.0.1
  crypto: ^3.0.3
  curved_navigation_bar: ^1.0.3
  expansion_tile_card: ^3.0.0
  simple_ripple_animation: ^0.0.9
  flutter_svg: ^2.0.10+1
  google_maps_flutter: ^2.9.0
  location: ^7.0.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  geocoding: ^3.0.0
  geolocator: ^9.0.2
  flutter_image_compress: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: UbuntuBold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf

    - family: UbuntuLight
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf

    - family: UbuntuMedium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf

    - family: UbuntuRegular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

    - family: AldrichRegular
      fonts:
        - asset: assets/fonts/Aldrich-Regular.ttf

    - family: InterRegular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
